### ISSUE TITLE
bin/setup results in this error on WSL | `PSQL FOLDER PERMISSIONS`

### ISSUE THREAD

**Issue by mnyon-grandkru** [the-teacher/rails7-startkit#35] opened 2023-05-19 01:31 UTC
Here's the screenshot of the bin/setup call and the results. 

The specific error message is: 
```
/usr/share/rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:2028:in `utime': Permission denied @ apply2files - db/PGSQL/.keep (Errno::EACCES)
```

![image](https://github.com/the-teacher/rails7-startkit/assets/5750239/ee19a574-5f55-4920-8002-c043b40e63cc)

**Comment by the-teacher** [comment] 2023-05-21 13:09
@mnyon-grandkru hello sir!

Please from the root of the project do the following commands:

```sh
ls -al db/
```

```sh
ls -al db/PGSQL
```

**Comment by mvpxtech** [comment] 2023-08-13 00:00
I am also encountering this error

![ERROR PGSQL](https://github.com/the-teacher/rails7-startkit/assets/73921675/9d418c92-fa3c-4fd2-a070-24adde50394b)

**Comment by the-teacher** [comment] 2023-08-13 20:18
@mvpxtech Hi! Thank you for the report!
I will try to find a person who uses Win to debug the case
I do not have an answer and can not to reproduce and debug it somehow. Sorry

If you find a solution, please share

**Comment by the-teacher** [comment] 2023-08-13 20:20
Ah, I see. It is because of permissions for the PGSQL folder
Mac is managing it out of the box. for the windows it is not so. Not sure about Linux.

At least I have a direction. Your information is very helpful. Thank you!

**Comment by the-teacher** [comment] 2023-08-26 16:01
@mnyon-grandkru @mvpxtech 
I'm requesting a check of the most recent version 
https://github.com/the-teacher/rails7-startkit/commit/11a5c05e49e442e458b24945982941a12fbb4f56

**Comment by the-teacher** [comment] 2023-09-02 19:58
@mnyon-grandkru @mvpxtech
After recent updates this issue has to be fixed.

Tested on MacOs and Linux (Debian)
I'm waiting for any feedback to close this issue.
Anyone is welcome to test and provide a feedback.

**Comment by the-teacher** [comment] 2023-09-08 19:38
Testing on Linux and Windows showed good results.
<img width="810" alt="Screenshot 2023-09-08 at 22 20 38" src="https://github.com/the-teacher/rails7-startkit/assets/496713/e0f12baa-9b1c-4a0f-803f-38a370550216">
<img width="1184" alt="Screenshot 2023-09-08 at 22 19 14" src="https://github.com/the-teacher/rails7-startkit/assets/496713/af4c4eef-d87c-4235-9b69-db8d3ebdaad0">

**Closed by the-teacher** 2023-09-08 19:38 UTC
Labels: help wanted, WINDOWS
